export const CREATE_MESSAGE_REQUEST = 'CREATE_MESSAGE_REQUEST';
export const CREATE_MESSAGE_SUCCESS = 'CREATE_MESSAGE_SUCCESS';
export const CREATE_MESSAGE_FAILURE = 'CREATE_MESSAGE_FAILURE';

export const CREATE_CHAT_REQUEST = 'CREATE_CHAT_REQUEST';
export const CREATE_CHAT_SUCCESS = 'CREATE_CHAT_SUCCESS';
export const CREATE_CHAT_FAILURE = 'CREATE_CHAT_FAILURE';

export const DELETE_CHAT_REQUEST = 'DELETE_CHAT_REQUEST';
export const DELETE_CHAT_SUCCESS = 'DELETE_CHAT_SUCCESS';
export const DELETE_CHAT_FAILURE = 'DELETE_CHAT_FAILURE';

export const EDIT_CHAT_IMAGE_REQUEST = 'EDIT_CHAT_IMAGE_REQUEST';
export const EDIT_CHAT_IMAGE_SUCCESS = 'EDIT_CHAT_IMAGE_SUCCESS';
export const EDIT_CHAT_IMAGE_FAILURE = 'EDIT_CHAT_IMAGE_FAILURE';

export const DELETE_MESSAGE_REQUEST = 'DELETE_MESSAGE_REQUEST';
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS';
export const DELETE_MESSAGE_FAILURE = 'DELETE_MESSAGE_FAILURE';

export const GET_ALL_CHAT_REQUEST = 'GET_ALL_CHAT_REQUEST';
export const GET_ALL_CHAT_SUCCESS = 'GET_ALL_CHAT_SUCCESS';
export const GET_ALL_CHAT_FAILURE = 'GET_ALL_CHAT_FAILURE';
