export const CREATE_STORY_REQUEST = "CREATE_STORY_REQUEST";
export const CREATE_STORY_SUCCESS = "CREATE_STORY_SUCCESS";
export const CREATE_STORY_FAILURE = "CREATE_STORY_FAILURE";

export const GET_USER_STORY_REQUEST = "GET_USER_STORY_REQUEST";
export const GET_USER_STORY_SUCCESS = "GET_USER_STORY_SUCCESS";
export const GET_USER_STORY_FAILURE = "GET_USER_STORY_FAILURE";

export const GET_ALL_STORY_REQUEST = "GET_ALL_STORY_REQUEST";
export const GET_ALL_STORY_SUCCESS = "GET_ALL_STORY_SUCCESS";
export const GET_ALL_STORY_FAILURE = "GET_ALL_STORY_FAILURE";

export const EDIT_STORY_REQUEST = "EDIT_STORY_REQUEST";
export const EDIT_STORY_SUCCESS = "EDIT_STORY_SUCCESS";
export const EDIT_STORY_FAILURE = "EDIT_STORY_FAILURE";

export const DELETE_STORY_REQUEST = "DELETE_STORY_REQUEST";
export const DELETE_STORY_SUCCESS = "DELETE_STORY_SUCCESS";
export const DELETE_STORY_FAILURE = "DELETE_STORY_FAILURE";

export const LIKE_STORY_REQUEST = "LIKE_STORY_REQUEST";
export const LIKE_STORY_SUCCESS = "LIKE_STORY_SUCCESS";
export const LIKE_STORY_FAILURE = "LIKE_STORY_FAILURE";
